[project]
name = "atlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kevinlam404", email = "kevinklam223@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "earthengine-api>=1.7.45",
    "geemap>=0.38.8",
    "geopandas>=1.1.4",
    "jupyterlab>=4.6.4",
    "pandas>=3.0.6",
    "rasterio>=1.5.1",
]

[project.scripts]
atlas = "atlas:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
